//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yemeksepeti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restoranlar
    {
        public int id { get; set; }
        public string restoranadı { get; set; }
        public Nullable<int> minimumsiparis { get; set; }
        public Nullable<double> restoranpuan { get; set; }
        public string acıklama { get; set; }
    }
}
