//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yemeksepeti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yemek
    {
        public int yemek_id { get; set; }
        public string yemek_adı { get; set; }
        public Nullable<int> fiyat { get; set; }
        public string restoran_adı { get; set; }
    }
}
